# Generated by Django 4.2.7 on 2023-11-13 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('genre', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
