# Generated by Django 5.0 on 2023-12-05 15:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0003_alter_author_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('isbn', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('format', models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('Ebook', 'Ebook'), ('Other', 'Other')], default='Other', max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=14)),
                ('language', models.CharField(default='English', max_length=255)),
                ('remaining_books', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('genre', models.CharField(blank=True, default='Other', max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
