# Generated by Django 4.2.7 on 2023-11-13 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('format', models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('Ebook', 'Ebook'), ('Other', 'Other')], default='Other', max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
