# Generated by Django 4.2.7 on 2023-11-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='Other', max_length=255, null=True),
        ),
    ]
