# Generated by Django 4.2.1 on 2023-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_language_book_price_book_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Remaining Books'),
        ),
    ]
