# Generated by Django 4.2.1 on 2023-12-06 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_remaining_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=14, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
