# Generated by Django 4.2.1 on 2023-12-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
