# Generated by Django 4.2.7 on 2023-12-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_remaining_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=14),
        ),
    ]
