# Generated by Django 4.2.7 on 2023-11-15 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_book_options_book_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('Suggestion', 'Suggestion'), ('Complaint', 'Complaint'), ('Enquiry', 'Enquiry'), ('Other', 'Other')], default='Other', max_length=100)),
                ('title', models.CharField(max_length=1255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
