# Generated by Django 4.2.1 on 2023-11-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_language_book_price_book_price_currency_and_more'),
        ('cart', '0002_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
