# Generated by Django 4.2.1 on 2023-12-06 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
